### ISSUE TITLE
Add an image or gif  to the homepage that shows welcoming features

### ISSUE THREAD

**Issue by Crist04** [Crist04/SignUpPage#22]

**Comment by Pragya2056** [comment]
If you specify what kind of image or gif - I can do it. 
Please assign it to me.

**Comment by kashish0604** [comment]
hey @Crist04 can you assign this issue to me  ican work on it

**Comment by Luci04** [comment]
assign this to me this can be my first conribution

**Comment by Crist04** [comment]
ok
